// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3uNn53rmqa0ZYmMmwONDXm6YLaDSvui4',
    appId: '1:63072787122:web:1f3f1456d6b3fb836907ab',
    messagingSenderId: '63072787122',
    projectId: 'my-tourim-app-123',
    authDomain: 'my-tourim-app-123.firebaseapp.com',
    storageBucket: 'my-tourim-app-123.firebasestorage.app',
    measurementId: 'G-JHMXJRK022',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYzFF51rmwzGvQhdnPR6JQwNePzXZKVq0',
    appId: '1:63072787122:android:e28b17d538aebbb56907ab',
    messagingSenderId: '63072787122',
    projectId: 'my-tourim-app-123',
    storageBucket: 'my-tourim-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2lkRvWyb3E24H_uDVRIx4vVRwdXZAcQY',
    appId: '1:63072787122:ios:4f1ca2366c3528d46907ab',
    messagingSenderId: '63072787122',
    projectId: 'my-tourim-app-123',
    storageBucket: 'my-tourim-app-123.firebasestorage.app',
    iosBundleId: 'com.regisse.tourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2lkRvWyb3E24H_uDVRIx4vVRwdXZAcQY',
    appId: '1:63072787122:ios:4f1ca2366c3528d46907ab',
    messagingSenderId: '63072787122',
    projectId: 'my-tourim-app-123',
    storageBucket: 'my-tourim-app-123.firebasestorage.app',
    iosBundleId: 'com.regisse.tourism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3uNn53rmqa0ZYmMmwONDXm6YLaDSvui4',
    appId: '1:63072787122:web:f55fcec82b05e1c96907ab',
    messagingSenderId: '63072787122',
    projectId: 'my-tourim-app-123',
    authDomain: 'my-tourim-app-123.firebaseapp.com',
    storageBucket: 'my-tourim-app-123.firebasestorage.app',
    measurementId: 'G-BCHL8667PR',
  );
}
