import 'package:flutter/foundation.dart' show kDebugMode, kIsWeb;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'config/app_config.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'app.dart';
import 'providers/theme_provider.dart';
import 'providers/destination_provider.dart';
import 'providers/booking_provider.dart';
import 'providers/auth_provider.dart';
import 'providers/language_provider.dart';
import 'providers/favorites_provider.dart';
import 'providers/personalization_provider.dart';
import 'providers/payment_methods_provider.dart';
import 'services/api_analytics_service.dart';
import 'services/analytics_service.dart';
import 'services/mock_analytics_service.dart';
import 'repositories/api_booking_repository.dart';
import 'repositories/api_destination_repository.dart';
import 'repositories/hybrid_auth_repository.dart';
import 'repositories/dev_bypass_auth_repository.dart';
import 'repositories/firebase_auth_repository.dart';
import 'repositories/mock_booking_repository.dart';
import 'repositories/mock_destination_repository.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    final config = AppConfig.fromEnvironment();
    config.validate();

    await Firebase.initializeApp(
      options: kIsWeb ? DefaultFirebaseOptions.currentPlatform : null,
    );

    if (kDebugMode) {
      debugPrint('Firebase apps: ${Firebase.apps.map((a) => a.name).toList()}');
      debugPrint('Default projectId: ${Firebase.app().options.projectId}');
      debugPrint('USE_GRAPHQL_API: ${config.useGraphQlApi}');
    }

    final destinationRepository = config.useGraphQlApi
        ? ApiDestinationRepository(
            endpoint: config.graphQlEndpoint,
          )
        : const MockDestinationRepository();

    final bookingRepository = config.useGraphQlApi
        ? ApiBookingRepository(
            endpoint: config.graphQlEndpoint,
          )
        : MockBookingRepository();

    final authRepository = DevBypassAuthRepository.isEnabled
        ? DevBypassAuthRepository()
        : config.useGraphQlApi
            ? HybridAuthRepository(
                endpoint: config.graphQlEndpoint,
                authToken: config.graphQlAuthToken,
              )
            : const FirebaseAuthRepository();

    final analyticsService = config.useGraphQlApi
        ? ApiAnalyticsService(
            endpoint: config.graphQlEndpoint,
          )
        : MockAnalyticsService();

    runApp(
      MultiProvider(
        providers: [
          Provider<AnalyticsService>.value(value: analyticsService),
          ChangeNotifierProvider(create: (_) => ThemeProvider()),
          ChangeNotifierProvider(
            create: (_) => DestinationProvider(repository: destinationRepository),
          ),
          ChangeNotifierProvider(
            create: (_) => BookingProvider(
              repository: bookingRepository,
              analytics: analyticsService,
            ),
          ),
          ChangeNotifierProvider(
            create: (_) => FavoritesProvider(analytics: analyticsService),
          ),
          ChangeNotifierProvider(create: (_) => PersonalizationProvider()),
          ChangeNotifierProvider(create: (_) => PaymentMethodsProvider()),
          ChangeNotifierProvider(
            create: (_) => AuthProvider(repository: authRepository),
          ),
          ChangeNotifierProvider(create: (_) => LanguageProvider()..loadLocale()),
        ],
        child: const TourismApp(),
      ),
    );
  } catch (e) {
    final details = kDebugMode ? '$e' : '';
    runApp(_StartupErrorApp(details: details));
  }
}

class _StartupErrorApp extends StatelessWidget {
  final String details;

  const _StartupErrorApp({required this.details});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SafeArea(
          child: Center(
            child: Padding(
              padding: const EdgeInsets.all(24),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Icon(Icons.error_outline, size: 48),
                  const SizedBox(height: 12),
                  const Text(
                    'App failed to start',
                    style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 8),
                  const Text(
                    'Check runtime configuration values and try again.',
                    textAlign: TextAlign.center,
                  ),
                  if (details.isNotEmpty) ...[
                    const SizedBox(height: 12),
                    Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: Colors.black.withOpacity(0.06),
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: Text(
                        details,
                        style: const TextStyle(fontFamily: 'monospace'),
                      ),
                    ),
                    const SizedBox(height: 10),
                    FilledButton.icon(
                      onPressed: () async {
                        await Clipboard.setData(ClipboardData(text: details));
                        if (context.mounted) {
                          ScaffoldMessenger.of(context).showSnackBar(
                            const SnackBar(
                              content: Text('Error details copied to clipboard.'),
                              behavior: SnackBarBehavior.floating,
                            ),
                          );
                        }
                      },
                      icon: const Icon(Icons.copy),
                      label: const Text('Copy details'),
                    ),
                  ],
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}