import 'package:flutter/foundation.dart' show kDebugMode, kIsWeb;
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'app.dart';
import 'providers/theme_provider.dart';
import 'providers/destination_provider.dart';
import 'providers/booking_provider.dart';
import 'providers/auth_provider.dart';
import 'providers/language_provider.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

   await Firebase.initializeApp(
    options: kIsWeb ? DefaultFirebaseOptions.currentPlatform : null,
  );

  if (kDebugMode) {
    debugPrint('Firebase apps: ${Firebase.apps.map((a) => a.name).toList()}');
    debugPrint('Default projectId: ${Firebase.app().options.projectId}');
  }
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => DestinationProvider()),
        ChangeNotifierProvider(create: (_) => BookingProvider()..loadSampleBookings()),
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => LanguageProvider()..loadLocale()),
      ],
      child: const TourismApp(),
    ),
  );
}